### PR TITLE
Convert build into a gulp task

### LINKED ISSUE #19: Convert build script to node
Since there's a gulp file now, perhaps we should use gulp to run the build process? If so, we may as well use npm to pull down the markdown dependency too and just rewrite the script in node.

### PR DESCRIPTION
**Pull request by glenjamin**
Fixes #19

### CODE REVIEW

**Comment by chicgeek** [comment]
This is something I wanted to ask about. With the current .md process we can't add CSS classes that would be useful for FE work. How do you see this working?

**Comment by glenjamin** [comment]
I've not thought heavily about it, HTML is enabled in the markdown parser, so we could sack off the weird made-up `--ROW` stuff and put some layout markup in there.

It partially depends how much people care about the markdown, we could just go all HTML instead.

**Comment by iparr** [comment]
Two options could be:

* Using a markdown engine like *kramdown* (which is Ruby, but I think a Node-equivalent like [*Kramed*](https://github.com/GitbookIO/kramed) would do the same) would allow more 'advanced' markdown like the following:

```
## A heading
{: .this-is-a-classname}
```

This upsets me a little as a purist though :)
* Splitting the markdown up into another (arguably more fitting) format - say a .json feed for the meetups and places and everything else could be accommodated within some sort of templating system, allowing you to add classes without those who add content worrying about them.

I'd be happy to sling together a prototype if you think it could help.

**Comment by ejs** [comment]
The Leeds list works the second way. Groups are stored as json, which gets run through a basic go script and then into a template.

https://github.com/emgee/leedsgeeks

I know the guy who built it, he be very happy if we borrowed it.

**Comment by ejs** [comment]
I've added issue #21 so that we can merge the conversion to gulp and talk more about making FE work easier/possible

**Pull request merged**
