### PR TITLE
Remove the dead

### PR DESCRIPTION
**Pull request by ejs**
None of these seem usefully live any more, which is a shame.

### CODE REVIEW

**Comment by garym** [comment]
Looks like it's last tweet was Jan 12th 2016 - is it a bit premature to take it out? Ah, I see iparr got here before me! :)

**Comment by ejs** [comment]
its still tweeting, but there's been 3 tweets over the last 6 months. The jan one is for something in Chesterfield. Would you actually point someone at it for more information?

If it became more lively it'd be easy enough to re-add, and if we're not listing a … very sick twitter account it could prompt someone to make a more live one (through discussions like this one ;) )

**Comment by ClearCarbon** [comment]
I think its Jag (https://twitter.com/Jagusti) who runs the sheffieldgeeks twitter account, if its not him he should know who is running it now.

**Comment by glenjamin** [comment]
We could start using the mailing list?

**Comment by ejs** [comment]
we could indeed. Will happily un-cull anything that reveals it wasn't dead, just sleeping.

**Comment by garym** [comment]
Gitorious is pretty dead - if there is demand for a github mirror we could look at using gitlab.

Anyway, having completed my review, I am happy that these can be culled until we have a reason to reinstate them.

**Comment by graphiclunarkid** [comment]
I think @ClearCarbon is right, it's one of the old GIST people who runs the SheffieldGeeks twitter account, most likely Jag. Maybe we should just talk to the account via Twitter and see whether they have plans or would be happy to pass over the reigns?!

**Comment by ejs** [comment]
I have no desire to take over the twitter (or any other) account myself, but if anyone is interested in either taking them over or setting up a new alternative I'm strongly in favor of that. The goal of this pull request was mostly to expose the current state, spark this conversation, and if nothing changed get the basically inactive things off the top of the page.

The same goes for the mailing list ; I'm absolutely in favor of us using it more (or setting up a new one), but we shouldn't list it in its current state.

Does anyone want to step forward and start bringing things back to life?

**Comment by garym** [comment]
The silence following that is deafening. I would be worried that this is the kind of thing that could be a lot of effort without automation. I'm thinking of adding a few plugins to burritobot, including one to tweet topic changes. I don't know if that would be a satisfactory solution.

**Comment by ejs** [comment]
it would be a huge improvement, and wouldn't stop anyone else providing something more if they were unsatisfied. If you want to be really safe make a sheffgeeksbot twitter account for it or something.

**Pull request merged**
