### PR TITLE
Add basic gulpfile for future front end work

### PR DESCRIPTION
**Pull request by chicgeek**

### CODE REVIEW

**Comment by iparr** [comment]
Hey. Just purely out of interest: is there a plan to do something more erm, imaginative, with this beautiful website? :-)

**Comment by chicgeek** [comment]
Maaaayyyyyybe. :)

**Comment by chicgeek** [comment]
What gave it away? The 'future front end work' part?

**Comment by jwheare** [comment]
I think @iparr was asking for more lens flare and construction gifs.

**Comment by iparr** [comment]
I'd be interested in seeing any plans etc. but of course this is entirely because I am nosey and I would not want to get in the way. I don't want to be *that* guy. Have fun.

**Comment by chicgeek** [comment]
I claim no ownership. We can have a powow over a pint, if you'd like?

**Comment by glenjamin** [comment]
Probably don't need to gitignore the source maps, LGTM though

**Comment by chicgeek** [comment]
I was in two minds about the source maps. We can commit/unignore them with later work. :+1:

**Comment by iparr** [comment]
Happy to @chicgeek , if it'd help. I think there is some interesting potential. Let's take it to Twitter so as not to annoy commit-ers!

**Comment by garym** [comment]
why would it annoy committers? I'm happy to hear ideas.

**Comment by glenjamin** [comment]
There's an unsubscribe button if anyone wants to opt out, keeping it here might be good so we have a record with the repo.

**Comment by chicgeek** [comment]
My initial intent is to start by just styling the basic atoms/components. More drastic layout changes and any 'real design' would happen afterwards.

**Comment by iparr** [comment]
Sorry @garym , @glenjamin - I was referring to arranging an over-pint powow! Wouldn't want to obscure any ideas.

Sounds great idea @chicgeek

**Pull request merged**
